sonar.projectKey=LeoMasevski_learn-smart
sonar.organization=leomasevski

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=learn-smart
#sonar.projectVersion=1.0

sonar.sources=backend/src,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.test.ts,**/*.test.tsx,**/__tests__/**

sonar.sourceEncoding=UTF-8